server:
  port: 80


spring:
  application:
    name: nav
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/recommend
    username: root
    password: root
#  mvc:
#    view:
#      suffix: .html
#      prefix: /
  thymeleaf:
    prefix: classpath:/view/

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
